config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
    
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/pitches' => 'pitches#index'
  get '/contacts' => 'contacts#index'
  
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :pitches
  end
  
  resources :pitches
  resources :statuses
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pitch.rb
class Pitch < ApplicationRecord
  belongs_to :user
  belongs_to :status
end

app/models/status.rb
class Status < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  
  has_many :pitches
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates_confirmation_of :password
  
  has_many :pitches
  
  has_secure_password
  
  def collect_statuses(user)
    status_array = []  
    user.pitches.each do |pitch|
      status_array << pitch.status.id
    end
    status_finder(status_array)
  end
  
  def status_finder(status_array)
    found_statuses = []
    status_array.each do |status|
      found_statuses << Status.find(status)
    end
    found_statuses
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authorize
  
  def index
  end
  
end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    render :index
  end
  
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  before_action :security_redirect
  before_action :authorize
  before_action :set_user
  
  def index
    @user = User.find(params[:user_id])
    @pitches = @user.pitches
  end
  
  def show
    @pitch = Pitch.find(params[:id])
  end
  
  def new
    @pitch = Pitch.new()
    @status_options = Status.all.map{ |c| [c.title, c.id] }
  end
  
  def create
    @status_options = Status.all.map{ |c| [c.title, c.id] }
    @pitch = @user.pitches.new(pitch_params)
    if @pitch.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end
  
  def edit
    @status_options = Status.all.map{ |c| [c.title, c.id] }
    @pitch = Pitch.find(params[:id])
  end
  
  def update
    @status_options = Status.all.map{ |c| [c.title, c.id] }
    @pitch = @user.pitches.find(params[:id])
    if @pitch.update(pitch_edit_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  
  def destroy
    @pitch = @user.pitches.find(params[:id])
    @pitch.destroy
    redirect_to user_path(@user)
  end
  
  private
  
  def set_user
    @user = User.find(session[:user_id])
  end
  
  def pitch_params
    params.require(:pitch).permit(:title, :content, :user_id, :status_id)
  end
  
  def pitch_edit_params
    params.require(:pitch).permit(:title, :content, :status_id)
  end

  
  def security_redirect
    if session[:user_id].nil?
      redirect_to login_path
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end
  
  def destroy
    session.clear
    redirect_to '/login'
  end
  
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  
  def index
    @user = User.find(session[:user_id])
    @statuses = @user.collect_statuses(@user)
  end
  
  def new
    @status = Status.new()
  end
  
  def show
    @pitches = @status.pitches
  end
  
  def create
    @status = Status.new(status_params)
    if @status.save
      redirect_to status_path(@status)
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @status.update(status_params)
      redirect_to status_path(@status)
    else
      render :edit
    end
  end
  
  def destroy
    @status.delete
    redirect_to statuses_path
  end
  
  private 
  
  def set_status
    @status = Status.find(params[:id])
  end
  
  def status_params
    params.require(:status).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def new
    @user = User.new
  end
  
  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to login_path
    else 
      redirect_to '/signup'
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @user.update(user_edit_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end
  
  def destroy
    session.clear
    @user.destroy
    redirect_to "/"
  end
  
  
  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def user_edit_params
    params.require(:user).permit(:name, :email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<body class="homepage-body">
  <div class="welcome-banner">
    <% if current_user %>
      <h1><%= "Welcome back, #{current_user.name}!" %></h1>
    <% else %>
      <h1>Welcome!</h1>
    <% end %>
  </div>  
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pitcher</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application_css', media: 'all' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pitcher</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-brand">
          <% if current_user %>
            <li><p>Signed in as <%= link_to current_user.name, user_path(current_user)  %> | <%= link_to 'Logout', '/logout' %> | <%= link_to "View All Statuses", statuses_path %></p></li>
          <% else %>
            <li><p><%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %></p></li>
          <% end %>
        </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  <body>
  
  <%= yield %>
  
  </body>
</html>

app/views/pitches/_form.html.erb
<%= form_for [@user, @pitch] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  
  <%= f.label :content %>
  <%= f.text_field :content %>
  
  <div class="statuses">
    <%= f.label :status %>
    <%= f.select(:status_id, @status_options) %>
  </div>
  
  <%= f.submit %>

<% end %>

app/views/pitches/edit.html.erb
<h2>Edit pitch: <%= @pitch.title %></h2>

<%= render partial: "form" %>

app/views/pitches/new.html.erb
<h2>Create a new pitch!</h2>

<%= render partial: "form" %>

app/views/pitches/show.html.erb
<div>
  
  <p>
    Title: <%= @pitch.title %>
  </p>
  
  <p>
    Content: <%= @pitch.content %>
  </p>
  
  <p>
    Status: 
    <% if @pitch.status %>
      <%= @pitch.status.title %>
    <% else %>
      New
    <% end %>
  </p>
  
  <p>
    <%= link_to "Edit Pitch", edit_pitch_path(@pitch) %>
    <%= link_to "Create Status", new_status_path %>
  </p>
  
</div>

app/views/statuses/_form.html.erb
<div class="jumbotron container">
  <%= form_for @status do |f| %>
  
  <%= f.label :title %>
  <%= f.text_field :title %>
  
  <%= f.submit %>
  
  <% end %>
  
  
</div>

app/views/statuses/index.html.erb
<div>
  
  <% @statuses.each do |status| %>
    <%= link_to status.title, status_path(status) %>
  <% end %>
  
</div>

app/views/statuses/new.html.erb
<h2>Create a new status!</h2>

<%= render partial: "form" %>

app/views/users/_form.html.erb
<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  <% unless @hide_password_entry_form %>
    Password: <%= f.password_field :password %>
    Password Confirmation: <%= f.password_field :password_confirmation %>
  <% end %>
  <%= f.submit %>

<% end %>

app/views/users/edit.html.erb
<h1>Hello, <%= current_user.name %>. Edit your profile here.<h1>
  
  <%= form_for @user do |f| %>

    Name: <%= f.text_field :name %>
    Email: <%= f.text_field :email %>
    <%= f.submit %>

  <% end %>

app/views/users/new.html.erb
<div class="container jumbotron sign-up-form">
<h1>Signup!</h1>

<%= render partial: "form" %>
</div>

app/views/users/new.html.haml
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<div class="jumbotron col-md-6 user-page-profile">
  <p class="user-page-text">Name: <%= current_user.name %></p>
  <p class="user-page-text">Email: <%= current_user.email %></p>
    <div>
      <%= link_to "Edit Account", edit_user_path(current_user) %>
      <%= link_to "Delete Account", user_path(current_user), method: :delete, data: { confirm: "Are you sure? This cannot be undone. It will delete all of your pitches and contacts forever." } %>
    </div>
</div>

<div class="jumbotron col-md-4 user-page-pitches">
  <ul class="user-page-text">
  Pitches: <% @user.pitches.each do |pitch| %>
              <li><%= link_to pitch.title, user_pitch_path(@user, pitch) %> | <%= link_to pitch.status.title, statuses_path %></li>
              <%= link_to "Edit Pitch", edit_user_pitch_path(@user, pitch) %>
              <%= link_to "Delete Pitch", user_pitch_path(@user, pitch), method: :delete, data: { confirm: "Are you sure?" } %>
            <% end %>
  </ul>
</div>

<div class="btn btn-default button-text-override">
  <%= link_to "Create a new pitch", new_user_pitch_path(@user) %>
</div>